spring.application.name=rest-api
spring.datasource.url=jdbc:postgresql://localhost:5434/restaurant_db
spring.datasource.username=restaurant_user
spring.datasource.password=restaurant_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

jwt.secret=1bALjy2raXlVavrjrFd++JtIA20oX99Pbi3MJ2nEgoAmm1HqGGsPFQWkoHZU0tegTAk1PGT82/US8Llp87hpGA==
jwt.expiration=86400000