-- Schema inicial: equivalente ao que o Hibernate gerava com ddl-auto=update

CREATE TABLE users (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(255) NOT NULL,
    email    VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role     VARCHAR(255) NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT ck_users_role CHECK (role IN ('CUSTOMER', 'WAITER', 'ADMIN'))
);

CREATE TABLE category (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    description VARCHAR(255)
);

CREATE TABLE menu_item (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255)   NOT NULL,
    description VARCHAR(255),
    price       NUMERIC(38, 2) NOT NULL,
    available   BOOLEAN
);

-- Tabela de junção do @ManyToMany entre MenuItem e Category
CREATE TABLE menu_item_categories (
    menu_item_id BIGINT NOT NULL,
    category_id  BIGINT NOT NULL,
    CONSTRAINT pk_menu_item_categories PRIMARY KEY (menu_item_id, category_id),
    CONSTRAINT fk_menu_item_categories_menu_item FOREIGN KEY (menu_item_id) REFERENCES menu_item (id),
    CONSTRAINT fk_menu_item_categories_category FOREIGN KEY (category_id) REFERENCES category (id)
);

CREATE TABLE restaurant_tables (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number       INTEGER      NOT NULL,
    capacity     INTEGER      NOT NULL,
    table_status VARCHAR(255) NOT NULL,
    CONSTRAINT uk_restaurant_tables_number UNIQUE (number),
    CONSTRAINT ck_restaurant_tables_status CHECK (table_status IN ('AVAILABLE', 'OCCUPIED', 'RESERVED'))
);

CREATE TABLE orders (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_status        VARCHAR(255)   NOT NULL,
    total_price         NUMERIC(38, 2) NOT NULL,
    created_at          TIMESTAMP(6),
    user_id             BIGINT         NOT NULL,
    restaurant_table_id BIGINT         NOT NULL,
    CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_orders_restaurant_table FOREIGN KEY (restaurant_table_id) REFERENCES restaurant_tables (id),
    CONSTRAINT ck_orders_status CHECK (order_status IN ('OPEN', 'CLOSED', 'CANCELLED'))
);

CREATE TABLE order_item (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantity          INTEGER        NOT NULL,
    unit_price        NUMERIC(38, 2) NOT NULL,
    observation       VARCHAR(255),
    order_item_status VARCHAR(255)   NOT NULL,
    order_id          BIGINT         NOT NULL,
    menu_item_id      BIGINT         NOT NULL,
    CONSTRAINT fk_order_item_order FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT fk_order_item_menu_item FOREIGN KEY (menu_item_id) REFERENCES menu_item (id),
    CONSTRAINT ck_order_item_status CHECK (order_item_status IN ('PENDING', 'PREPARING', 'READY', 'DELIVERED', 'CANCELLED'))
);
